### ISSUE TITLE
Add info to README what env variables are needed for the whole package

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#15]
We have been looking for that and had to skim through the source

**Comment by fabianmoronzirfas** [comment]
Maybe add a `env.example`

**Comment by fabianmoronzirfas** [comment]
@hsonne ☝️

**Comment by mrustl** [comment]
Screenshot of required environment variables (defined in Travis): 
![grafik](https://user-images.githubusercontent.com/11964451/64102639-a765ab00-cd70-11e9-8136-c4f1ca473870.png)

**Comment by fabianmoronzirfas** [comment]
Yesterday @hsonne and I found out that there are two other ENV variables missing.

```bash
    API_URL
    AUTH0_AUDIENCE
    AUTH0_CLIENT_ID
    AUTH0_CLIENT_SECRET
    AUTH0_REQ_URL
    TOKEN_PROD # <--
    ENDPOINT_PROD # <--
```
I think they should be more descriptive in their name. They are used for the Radolan Data API.

Also where should those be set? in `/home/$USER/.Renviron`? 

A section in the README would be great.

**Comment by hsonne** [comment]
So far, I have added a section in the README.
