### ISSUE TITLE
bug: functions cannot be called through opencpu API (possible realted to permissions)

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#18]
I have the opencpu api working and I'm getting responses from the default functions.

When I do a function call to the listed functions below (e.g. `api_get_bathingspot`, `api_get_rain` ) I get the error shown below.

```bash
$ curl http://localhost:8004/ocpu/library/fhpredict/R/api_get_bathingspot  -H "Content-Type: application/json" -d '{"user_id":3}'
> cannot open the connection
>
> In call:
> file(con, "w")
```

My guess is that this is related to permissions on the container. Any ideas how to test this?

```bash
$ curl http://localhost:8004/ocpu/library/fhpredict/info

		Information on package 'fhpredict'

Description:

Package:            fhpredict
Title:              R Package for the Project Flusshygiene
Version:            0.0.0.9000
Authors@R:          c(person(given = "Wolfgang", family = "Seis", role
                    = "aut", email =
                    "wolfgang.seis@kompetenz-wasser.de", comment =
                    c(ORCID = "0000-0002-7436-8575")), person(given =
                    "Hauke", family = "Sonnenberg", role = c("aut",
                    "cre"), email =
                    "hauke.sonnenberg@kompetenz-wasser.de", comment =
                    c(ORCID = "0000-0001-9134-2871")), person(given =
                    "Michael", family = "Rustler", role = "ctb", email
                    = "michael.rustler@kompetenz-wasser.de", comment =
                    c(ORCID = "0000-0003-0647-7726")), person(given =
                    "Fabian", family = "Mor\u00F3n Zirfas", role =
                    "ctb", email =
                    "moron-zirfas@technologiestiftung-berlin.de",
                    comment = c(ORCID = "0000-0002-9777-7283")),
                    person(given = "Kompetenzzentrum Wasser Berlin
                    gGmbH (KWB)", role = "cph"))
Description:        This R package provides all functions that are
                    required for the Web application that is developed
                    within the Flusshygiene project.
License:            MIT + file LICENSE
URL:                https://github.com/KWB-R/fhpredict
BugReports:         https://github.com/KWB-R/fhpredict/issues
Imports:            dplyr (>= 0.8.1), fs (>= 1.2.6), httr (>= 1.4.0),
                    jsonlite (>= 1.6), kwb.dwd (>= 0.1.0), kwb.utils
                    (>= 0.4.2), lubridate (>= 1.7.4), magrittr (>=
                    1.5), raster (>= 2.8.19), rstanarm (>= 2.18.2), sf
                    (>= 0.7.4), sp (>= 1.3.1), stringr (>= 1.4.0)
Suggests:           covr (>= 3.2.1), testthat (>= 2.2.1), knitr (>=
                    1.22), rmarkdown (>= 1.14)
Remotes:            github::kwb-r/kwb.dwd, github::kwb-r/kwb.utils
Encoding:           UTF-8
LazyData:           true
RoxygenNote:        6.1.1
VignetteBuilder:    knitr
RemoteType:         github
RemoteHost:         api.github.com
RemoteRepo:         fhpredict
RemoteUsername:     kwb-r
RemoteRef:          dev
RemoteSha:          f4d692bcc88f86879f975424446b204b61368d64
GithubRepo:         fhpredict
GithubUsername:     kwb-r
GithubRef:          dev
GithubSHA1:         f4d692bcc88f86879f975424446b204b61368d64
NeedsCompilation:   no
Packaged:           2019-09-03 10:04:16 UTC; root
Author:             Wolfgang Seis [aut]
                    (<https://orcid.org/0000-0002-7436-8575>), Hauke
                    Sonnenberg [aut, cre]
                    (<https://orcid.org/0000-0001-9134-2871>), Michael
                    Rustler [ctb]
                    (<https://orcid.org/0000-0003-0647-7726>), Fabian
                    Morón Zirfas [ctb]
                    (<https://orcid.org/0000-0002-9777-7283>),
                    Kompetenzzentrum Wasser Berlin gGmbH (KWB) [cph]
Maintainer:         Hauke Sonnenberg
                    <hauke.sonnenberg@kompetenz-wasser.de>
Built:              R 3.6.1; ; 2019-09-03 10:04:17 UTC; unix

Index:

api_add_model           Add a Model to the Database
api_add_rain            Add Rain Data Frame to Postgres Database Via
                        API
api_delete_model        Delete a Model from the Database
api_delete_rain         Delete Rain Data from Postgres Database Via API
api_get_bathingspot     Get Bathing Spot(s)
api_get_model           Read a Model from the Database
api_get_rain            Get Rain Data from the Postgres Database Via
                        API
api_get_users           Get Overview on Available Users
download_radolan        Download Radolan Files on DWD Server
get_area_coordinates    Return the coordinates of area assigned to
                        bathing spot
get_postgres_api_token
                        Get a Valid Token to Access the Postgres API
get_radolan_urls        Get URLs to Available Radolan Files on DWD
                        Server
get_radolan_urls_bucket
                        Get URLs to Binary Radolan Filed From
                        Flusshygiene's Amazon Bucket
postgres_delete         Send DELETE Request to Postgres API
postgres_get            Send GET Request to Postgres API
postgres_post           Send POST Request to Postgres API
provide_rain_data_for_bathing_spot
                        Provide Rain Data for one Bathing Spot
simple                  A io function
```

**Comment by fabianmoronzirfas** [comment]
Follow up.

It is a permission/security thing (See https://github.com/opencpu/opencpu/issues/300#issuecomment-396101850 and section 3.5 of [opencpu-server.pdf](https://opencpu.github.io/server-manual/opencpu-server.pdf)). Like recommended in this issue https://github.com/opencpu/opencpu/issues/175 the `getwd()` working dir should be used. 

I also ran the example from the issue and do get an result.
Where is fhpredict writing files to?
```bash
$ curl http://localhost:8004/ocpu/library/utils/R/write.csv -d 'x=iris&file="myiris.csv"'
>/ocpu/tmp/x022b84a5f1f059/R/.val
>/ocpu/tmp/x022b84a5f1f059/R/write.csv
>/ocpu/tmp/x022b84a5f1f059/source
>/ocpu/tmp/x022b84a5f1f059/console
>/ocpu/tmp/x022b84a5f1f059/info
>/ocpu/tmp/x022b84a5f1f059/files/DESCRIPTION
>/ocpu/tmp/x022b84a5f1f059/files/myiris.csv
# then 
$ curl http://localhost:8004/ocpu/tmp/x022b84a5f1f059/files/myiris.csv
>"","Sepal.Length","Sepal.Width","Petal.Length","Petal.Width","Species"
>"1",5.1,3.5,1.4,0.2,"setosa"
>"2",4.9,3,1.4,0.2,"setosa"
>"3",4.7,3.2,1.3,0.2,"setosa"
>"4",4.6,3.1,1.5,0.2,"setosa"
>"5",5,3.6,1.4,0.2,"setosa"
>"6",5.4,3.9,1.7,0.4,"se
#(…)
```

**Comment by hsonne** [comment]
https://github.com/KWB-R/fhpredict/blob/25c03628d69bc50312ccab68254cf3b843ffb602/R/get_postgres_api_token.R#L14

**Comment by fabianmoronzirfas** [comment]
> https://github.com/KWB-R/fhpredict/blob/25c03628d69bc50312ccab68254cf3b843ffb602/R/get_postgres_api_token.R#L14

So this is the function call where it is failing? When getting a new token?
I guess we should check if the actually are on `$HOME`

**Comment by hsonne** [comment]
This is the error message that you get when you do not have write permissions. For example, I do not have permission to write to `C:/Programme` and get the reported error:
```
> writeLines("xxx", "C:/Programme/abc.txt")
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") :
  cannot open file 'C:/Programme/abc.txt': Permission denied
```
I use the file `~/.postgres_api_token` to store the token that is required to access the API. 
Maybe I should not use `"~"` but `Sys.getenv("HOME")` instead? Who has access to the home directory?

**Comment by fabianmoronzirfas** [comment]
Okay. When I get the opencpu docs right every function call from the outside world lives in his own session folder. So writing to `./file` is not an option. I will run some test to find out who actually the user is that does the function calls and if we can find a persistent location where we can write files

**Comment by hsonne** [comment]
I thought about using a location within the R package itself: `system.file("extdata")`. I will try this next.

**Comment by mrustl** [comment]
I already successfully read a config file stored in **inst/extdata/configs/dummy** (https://github.com/KWB-R/kwb.qmra/tree/master/inst/extdata/configs/dummy)  from my R package **kwb.qmra** with opencpu:

https://github.com/KWB-R/kwb.qmra/blob/master/inst/www/js/app.js#L6

https://kwb-r.ocpu.io/kwb.qmra/ 

@fabianmoronzirfas may be it is also possible to write to such an folder from opencpu.

**Comment by mrustl** [comment]
For local debugging the following should work: 

```
install.packages(c("remotes", "opencpu"), repos = "https://cloud.r-project.org")
remotes::install_github("kwb-r/fhpredict@dev")
opencpu::ocpu_start_server()
```
[2019-09-03 15:26:36] OpenCPU single-user server, version 2.1.3
[2019-09-03 15:26:36] Starting 2 new worker(s). Preloading: opencpu, lattice
[2019-09-03 15:26:37] READY to serve at: http://localhost:5656/ocpu

![grafik](https://user-images.githubusercontent.com/11964451/64177232-5da7be00-ce5f-11e9-8848-bc970552e990.png)

**Comment by fabianmoronzirfas** [comment]
I installed the pkg with a ref set to 942d467 but I still get the same error.

**Comment by hsonne** [comment]
@fabianmoronzirfas Can you have a look into the kern.log file as described in https://opencpu.github.io/server-manual/opencpu-server.pdf?

"One nice way to debug a security profile is by monitoring the kern.logfile while using OpenCPU:
`sudo tail -f /var/log/kern.log | grep opencpu`
If any Rpackage or process called from OpenCPU attempts to do something that is not allowed in the current security profile, a line containing DENIED is printed to kern.log."

**Comment by fabianmoronzirfas** [comment]
Been there. The file does not exist. There seems to be an issue with docker and apparmor. I can write to `/tmp`. 

I’ll do a test and report back

**Comment by fabianmoronzirfas** [comment]
I have the problem that apparmor seems not to be working in the container. This is an issue I can't solve on the fly.  


I wrote a little test lib and I can confirm that I can write to `/tmp` https://github.com/fabianmoronzirfas/rtestlib

write the file 
```bash
curl http://localhost:8004/ocpu/library/rtestlib/R/writefile/json -d 'path="/tmp/file"'

```
read the file 
```bash
curl http://localhost:8004/ocpu/library/rtestlib/R/readfile/json -d 'path="/tmp/file"'
```

So for the time being we should write the token there and investigate further and keep this issue open.

**Comment by fabianmoronzirfas** [comment]
This is the error 

```text
AppArmor not available. Running OpenCPU without security profile but with rlimits.
```
And these are some reference links

- https://docs.docker.com/engine/security/apparmor/
- https://cloud.google.com/container-optimized-os/docs/how-to/secure-apparmor
- https://github.com/opencpu/opencpu-server/tree/master/docker#security

**Comment by hsonne** [comment]
Are there environment variables defined that point to `/tmp` in the container? On Windows I have both `TMP` and `TEMP` defined:
```
> Sys.getenv("TMP")
[1] "C:\\Users\\hsonne\\AppData\\Local\\Temp"
> Sys.getenv("TEMP")
[1] "C:\\Users\\hsonne\\AppData\\Local\\Temp"
```

**Comment by fabianmoronzirfas** [comment]
Nope they are not. But we can define them both.

**Comment by hsonne** [comment]
Ok, then please define `TEMP` as `/tmp` and the function will put the file there (see 
5e1df1d)

**Comment by fabianmoronzirfas** [comment]
Done. And it is working! 

```bash
 curl http://localhost:8004/ocpu/library/fhpredict/R/api_get_users/json  -H "Content-Type: application/json" -d ''
[
{
    "id": 3,
    "firstName": "Flusshygiene",
    "lastName": "",
    "role": "creator",
    "protected": false,
(…)
]
```
