### ISSUE TITLE
Trailing slash in ENV API_URL

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#20]
@hsonne Does it make create any problems for R if the trailing slash in the environment variable `API_URL=http://example.com/api/v1/` is removed?

In my setup I'm' using a nginx reverse proxy. So in the end there wont be a domain name needed just the `/api/v1` mount point and nginx will take care of the routing to the api. Could you run some test to remove thew trailing slash at the end if it works remove it?

All other env vars of mine that set urls don't have the trailing slash and I would love to keep it consistent.

**Comment by hsonne** [comment]
No problem, we can omit the trailing slash.
