### ISSUE TITLE
Error Messages Improvements

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#45]
When running fhpredict v.0.8.0 and v0.8.1 I'm getting the following error

```json
{
  "data": {},
  "sucess": [false],
  "message": ["Error in get_postgres_api_token() : \n  is_valid_postgres_api_token(token) is not TRUE\n"]
}
```

This is not related to the changes I did for restricting access from the outside. The container can ping the outside world.

Any idea?

BTW ~~sucess~~ = success

**Comment by fabianmoronzirfas** [comment]
@hsonne ☝️  This is a blocker

**Comment by hsonne** [comment]
Please try with v0.9.0 (just pulled to master), @fabianmoronzirfas

**Comment by fabianmoronzirfas** [comment]
We are still getting this error when using v0.9.0

```json
{"body":{"data":{},"success":[false],"message":["Error in get_postgres_api_token() : \n  is_valid_postgres_api_token(token) is not TRUE\n"]}
```

**Comment by hsonne** [comment]
But renaming of "sucess" was a full success!

**Comment by fabianmoronzirfas** [comment]
I'm not sue how to debug this.
- When I look into the `/tmp` folder of the container the token file is not there.
- I also tried to make the ocpu container public again and I'm still getting this error.

**Comment by hsonne** [comment]
Are all environment variables updated to point to the new URLs?

**Comment by fabianmoronzirfas** [comment]
I'm pretty sure I did. The auth0 urls didn't change. I also roled back to fhpredict 0.7.0 and I'm still getting this error.

**Comment by fabianmoronzirfas** [comment]
The question is:

- Is this error coming form getting the auth token then it is on my side
- is the error coming from some change in the package then it is on your side

**Comment by hsonne** [comment]
@fabianmoronzirfas Can you try with fhpredict@dev? I just committed a change that aims at improving the error message.

**Comment by fabianmoronzirfas** [comment]
Okay. Getting a new error yay \o/: 

```
{"data":{},"success":[false],"message":["Error : No (microbiological) measurements stored for user_id = 9 and spot_id = 4.\n"]}
```

**Comment by fabianmoronzirfas** [comment]
Is there a function that allows me to verify that the connection to the api is working without spot and user. Just a ping call to e.g. `HOST/api/v1/`?

**Comment by hsonne** [comment]
I always use `fhpredict::api_get_users()`. The function does not need any arguments and returns the table of users.

**Comment by fabianmoronzirfas** [comment]
Seems to have dependencies 

```
No such list elements: 'data'
Available elements: 'doc', 'node'

In call:
kwb.utils::selectElements(result, "data")

```

**Comment by fabianmoronzirfas** [comment]
Hm. I'm not sure if the error message is right. I added measuerments to spot 41 user 9 but I' still getting this error when trying to get the rain data…
