### ISSUE TITLE
2 Different errors when calling build_model

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#48]
Not realted to #41

When calling build_model for spot 41 user 9 from the middlelayer I get the following error (with dev branch):

```json
{"data":{},"success":[false],"message":["Error in sprintf(\"%s_spot%d\", prefix, spot_id) : \n  invalid format '%d'; use format %s for character objects\n"]}
```

When calling it through the interface of opencpu i get the following errors:

```json
{
  "data": {},
  "success": [false],
  "message": ["Error : stat::step() failed for the following step numbers:\nstep = 1: Error in stats::step(object = null, scope = list(upper = full, lower = null),  : \n  AIC is -infinity for this model, so 'step' cannot proceed\n\nstep = 2: Error in stats::step(object = null, scope = list(upper = full, lower = null),  : \n  AIC is -infinity for this model, so 'step' cannot proceed\n\n"]
}

```

Don't know if they are related and it can wait until you are back at work @hsonne  :-)

**Comment by hsonne** [comment]
The first error means that `spot_id` given to `build_model()` was not an integer value as expected but a string (`character` in R)

The second error means that no valid model could be found. Needs to be discussed with @wseis what to do (what error message to show) in this case.

**Comment by fabianmoronzirfas** [comment]
Cool. I can confirm that if I send real values in the POT body I get the second error. Which is wired. Why does it say that there is no model found when I do a call to `build_model`?

**Comment by hsonne** [comment]
The most probable cause is a lack of data, i.e. not "no data" but not enough data points (i.e. pairs of rain and e. coli concentration) to build a (at least somehow) valid model.

**Comment by fabianmoronzirfas** [comment]
> Did you use random values?

No I used values from an existing bathingspot. Can you or @wseis provide data that definitely will pass?

**Comment by wseis** [comment]
How many data point did you use?

**Comment by fabianmoronzirfas** [comment]
> How many data point did you use?

I guess 20 or something like that. Would be good to have a dataset ready for testing that is confirmed to work.
