### ISSUE TITLE
Error when calling `build_model` for spot_id 41 user_id 9

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#58]
@hsonne 

- I used the some data provided by @wseis for havel (had to clean duplicates)
- I succesfuly created rain data
- I started the modeling process and created a model

The modeling process seems to work but I get the following message back
```plain
Error in loadNamespace(name) : there is no package called 'svglite' 
```
- I could **NOT** create a prediction

**Comment by hsonne** [comment]
@fabianmoronzirfas I found out that svglite is required by the opencpu package since its version 2.1.6
https://github.com/opencpu/opencpu/commit/d460d31100f98be1cc94aaf682ee75d383d324ff#diff-35ba4a2677442e210c23a00a5601aba3
Which version do we use?

**Comment by fabianmoronzirfas** [comment]
We use 2.1.5 https://github.com/technologiestiftung/flusshygiene/blob/master/packages/opencpu-base/Dockerfile#L1

**Comment by hsonne** [comment]
Without further investigation, we should just add "svglite" to the list of packages to be installed in 
https://github.com/technologiestiftung/flusshygiene/blob/225a6fbac4542fca8240125da4d00ad780704742/packages/opencpu-base/Dockerfile#L26
