### ISSUE TITLE
Please do versioning for your internal packages

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#61]
Since all other packages have pinned versions, it would be great if
```
Remotes: 
    github::kwb-r/kwb.dwd,
    github::kwb-r/kwb.flusshygiene,
    github::kwb-r/kwb.utils,
```

Would also get a version instead of installing from master. 
Since a week my build for fhpredict fails during the install of `kwb.flusshygiene` and I didn't change anything. I assume the dependencie contains some error.

**Comment by hsonne** [comment]
Good idea, I will pin the versions. Also, I propose to install the packages separately, one by one, in the Dockerfile (https://github.com/technologiestiftung/flusshygiene/blob/18bfa05db6d417377cc170775158ab2c02cc0019/packages/opencpu-fhpredict-api/Dockerfile). I hope that this helps to track the error further down.

@fabianmoronzirfas Could you please replace line 31 in Dockerfile with the following four lines (`force = TRUE` and `build_vignettes = FALSE` should not be required, using single quotes improves readability):
```
RUN  R -e "remotes::install_github('kwb-r/kwb.utils@v0.5.0', upgrade = 'never')"
RUN  R -e "remotes::install_github('kwb-r/kwb.dwd@v0.1.0', upgrade = 'never')"
RUN  R -e "remotes::install_github('kwb-r/kwb.flusshygiene@v0.3.0', upgrade = 'never')"
RUN  R -e "remotes::install_github('kwb-r/fhpredict@v0.11.0', upgrade = 'never')"
```

**Comment by fabianmoronzirfas** [comment]
> Good idea, I will pin the versions. Also, I propose to install the packages separately, one by one, in the Dockerfile ([technologiestiftung/flusshygiene:packages/opencpu-fhpredict-api/Dockerfile@`18bfa05`](https://github.com/technologiestiftung/flusshygiene/blob/18bfa05db6d417377cc170775158ab2c02cc0019/packages/opencpu-fhpredict-api/Dockerfile)). I hope that this helps to track the error further down.
> 
> @fabianmoronzirfas Could you please replace line 31 in Dockerfile with the following four lines (`force = TRUE` and `build_vignettes = FALSE` should not be required, using single quotes improves readability):
> 
> ```
> RUN  R -e "remotes::install_github('kwb-r/kwb.utils@v0.5.0', upgrade = 'never')"
> RUN  R -e "remotes::install_github('kwb-r/kwb.dwd@v0.1.0', upgrade = 'never')"
> RUN  R -e "remotes::install_github('kwb-r/kwb.flusshygiene@v0.3.0', upgrade = 'never')"
> RUN  R -e "remotes::install_github('kwb-r/fhpredict@v0.11.1', upgrade = 'never')"
> ```

Tried that. Still get the same build error.

```
 *** caught illegal operation ***
address 0x7f21caf03e20, cause 'illegal operand'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(name)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(loadNamespace(name), error = function(e) {    warning(gettextf("namespace %s is not available and has been replaced\nby .GlobalEnv when processing object %s",         sQuote(name)[1L], sQuote(where)), domain = NA, call. = FALSE,         immediate. = TRUE)    .GlobalEnv})
 8: ..getNamespace(c("rstan", "2.19.2"), "")
 9: get(classMetaName(cl), where)
10: methods::cacheMetaData(ns, TRUE, ns)
11: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
12: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
13: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
14: asNamespace(ns)
15: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
16: loadNamespace(package = package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, partial = TRUE)
17: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
18: suppressPackageStartupMessages(loadNamespace(package = package,     lib.loc = lib.loc, keep.source = keep.source, keep.parse.data = keep.parse.data,     partial = TRUE))
19: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, compress = compress, set.install.dir = set.install.dir)
20: tools:::makeLazyLoading("kwb.flusshygiene", "/usr/local/lib/R/site-library/00LOCK-kwb.flusshygiene/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/usr/local/lib/R/site-library/kwb.flusshygiene")
An irrecoverable exception occurred. R is aborting now ...
Illegal instruction
ERROR: lazy loading failed for package 'kwb.flusshygiene'
* removing '/usr/local/lib/R/site-library/kwb.flusshygiene'
Error: Failed to install 'kwb.flusshygiene' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpcHem8m/file65f409e0c/kwb.flusshygiene_0.3.0.tar.gz' had non-zero exit status
Execution halted
The command '/bin/sh -c R -e "remotes::install_github('kwb-r/kwb.flusshygiene@v0.3.0', upgrade = 'never')"' returned a non-zero code: 1
```

I'll try to install 

```
    pkgload
    praise
    RcppParallel
    isoband
    testthat

```
in the ocpubase like mentioned in https://github.com/technologiestiftung/flusshygiene/issues/241

**Comment by fabianmoronzirfas** [comment]
Installing the packages into the opencpu-base

Fixes this issue.
