### ISSUE TITLE
Add OpenCPU webhook "https://cloud.opencpu.org/ocpu/webhook"

### ISSUE THREAD

**Issue by mrustl** [KWB-R/fhpredict#7]
As  described here: https://www.opencpu.org/api.html#api-ci 

An overview of all KWB-R packages with OpenCPU Webhook is available here: 
- https://kwb-r.github.io/status or 
- https://kwb-r.ocpu.io/

It was configured as follows at https://github.com/KWB-R/fhpredict/settings/hooks/new: 

![webhook](https://user-images.githubusercontent.com/11964451/53222056-74798680-366c-11e9-86b4-16b0eaf232e7.jpg)

Subsequently we get this (https://developer.github.com/webhooks/#ping-event) 

![success](https://user-images.githubusercontent.com/11964451/53222211-0f726080-366d-11e9-9a2d-dc45e10f1575.jpg)

The webhook will push the R package after each commit to the cloud OpenCPU server at https://kwb-r.ocpu.io/fhpredict

**Comment by fabianmoronzirfas** [comment]
Nice. What approach would you suggest for the flusshygiene project:

- Use the opencpu servers?
- Run our own opencpu container?

**Comment by mrustl** [comment]
I don`t know but I think it might be simple for start with the cloud OpenCPU first. You should be able to connect with the OpenCPU API from your UI with this approach:
https://www.opencpu.org/jslib.html#lib-cors

**Comment by mrustl** [comment]
Maybe it is better to also put the UI into the inst/www/ folder of the R package as stated: 

> The recommended design for OpenCPU apps is to include the web pages in the R package. This results in a standalone application, which is easy to distribute and deploy and can also be used offline. Furthermore, it guarantees that the version of front-end and R code are in sync, and the package manager automatically takes care of dependencies when the app is installed on a server. 
[Jeroeen Ooms](https://www.opencpu.org/jslib.html#lib-cors)

I did a very dummy example for the R package [kwb.qmra](https://github.com/kwb-r/kwb.qmra) and proposed this approach to our partners but they prefered to do the UI development in Java. 

For my OpenCpu example, have a look at:
https://github.com/KWB-R/kwb.qmra/tree/master/inst/www
https://kwb-r.ocpu.io/kwb.qmra/www/
https://kwb-r.github.io/kwb.qmra/articles/web_app.html

**Comment by fabianmoronzirfas** [comment]
> I don`t know but I think it might be simple for start with the cloud OpenCPU first. You should be able to connect with the [OpenCPU API](https://www.opencpu.org/api.html) from your UI with this approach:
[opencpu.org/jslib.html#lib-cors](https://www.opencpu.org/jslib.html#lib-cors)

Okay. I'll give it a try next week. Thinking about it. We might need to read write from our DB and from a Redis instance. So we need to pass around some access keys for that. Means we either do a total env less approach and all the keys are passed to the package via the request or we need to run it in a own container where I can customize the env. We will see what is easier. (Currently I think running it in a container see https://github.com/technologiestiftung/fhpredict-opencpu)

> Maybe it is better to also put the UI into the inst/www/ folder of the R package as stated:(…)

Hm. We will have a express backend for the frontend. I don't want to handle the whole application on the client side. So putting it into the R package is not an option. You can see my "holistic application overview here https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=draw-io-flusshygiene-diagrams.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Ftechnologiestiftung%2Fflusshygiene-flowcharts%2Fmaster%2Fdraw-io-flusshygiene-diagrams.xml"

**Comment by mrustl** [comment]
Will have a look on your provided links (depsite the fact that I might get lost because I am no deeply into that topic). Anyway, I like that your are trying the OpenCPU approach so that we have a first use-case for this as currently apps (even quite compley ones) are soley written in [R shiny](https://shiny.rstudio.com/). I am really curious about our work and hope I can learn a lot!

Concerning your points: 
 I totally agree with you that separating your UI from the R package is indicated due to its complexity and think that containerization will be super helpful for increasing reproducibilty and minimise the dependency hell. 

For an initial test for requesting the OpenCPU API the weebhook solution to the cloud server is an fast and simple solution.

**Comment by mrustl** [comment]
I close this now as fhpredict is now deployed on https://kwb-r.ocpu.io/fhpredict

after pull request #3 was merged by @hsonne. So the webhook is working!

**Comment by mrustl** [comment]
@fabianmoronzirfas maybe the missing "tag" of current opencpu docker builds is important for you: see https://github.com/opencpu/opencpu/issues/246

But should be fixed with the next release of the docker image

**Comment by fabianmoronzirfas** [comment]
@mrustl thanks for the hint. Yes it is. Add my voice to it.
