### ISSUE TITLE
Adding functionality "bathing season only" to get_urls_bucket" function

### ISSUE THREAD

**Issue by wseis** [KWB-R/fhpredict#9]
It would be nice to have an additional option in the function to only extract the URLS which fall between May 1st and Sept 30th, given the start year and the end year, thus avoiding downloading unnecessary files.

Example:
From = 2008
To = 2018
time = Samplign time
Bathing_season_only = TRUE

**Comment by hsonne** [comment]
Check it out in the dev version:

```
remotes::install_github("kwb-r/fhpredict@dev")

x <- fhpredict::get_radolan_urls_bucket(from = "2010", to = "2010", bathing_season_only = TRUE)
head(x)
tail(x)
```
